#配置中心服务端
server:
  port: 8040
spring:
  application:
    name: kbj-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oopsMonster/kbj/      # 配置git仓库的地址
          search-paths: config-repo                    # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: oopsMonster                              # git仓库的账号
          password: wpsbns*ANYY123                                 # git仓库的密码
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://localhost:8080/eureka/
